[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.8.0"
env_logger = "0.11.3"
tokio = {version = "1.38.0", features=["full"] }
fancy_surreal = { path = "../../fancy_surreal" }
log = "0.4.21"
actix-files = "0.6.6"
serde = { version = "1.0.163", features = ["derive"] }
shared = { path = "../shared", features = ["backend"] }
