[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
fancy_surreal = { path = "../../fancy_surreal", optional = true }
chordlib = { path = "../../chordlib", features = ["html"] }
serde = { version = "1.0.163", features = ["derive"] }

[features]
backend = ["fancy_surreal"]
