[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
chordlib = { path = "../../chordlib", features = ["html"] }
serde = { version = "1.0.228", features = ["derive"] }
utoipa = { version = "4", optional = true }

[features]
backend = ["utoipa"]
